In [1]:
# Question 1: Write a function to compute 5/0 and use try/except to catch the exceptions


a = 5 
b = 0
try:
    c = a/b
    print(c)
except ZeroDivisionError:
     print("Division by zero not possible")


Division by zero not possible


In [2]:
# Question 2: Implement a Python program to generate all sentences where subject is in ["Americans",
# "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

output_list = [ (sub +' '+ verb + ' ' + obj) for sub in subjects for verb in verbs for obj in objects]
for op in output_list:
    print(op)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# Task 2

In [8]:
# Write a function so that the columns of the output matrix are powers of the input vector.
# The order of the powers is determined by the increasing boolean argument. Specifically, when
# increasing is False, the i-th output column is the input vector raised element-wise to the power
# of N - i - 1.


import numpy as np

def vandermonde_matrix(mtrx,n):
    mtrx=np.array(mtrx)
    for i in range(n):
        mtrx[:,i] **= i+1           
    return mtrx


rows = int(input("Enter number of rows in matrix: "))
clmns = int(input("Enter number of columns in matrix: "))
matrix = np.zeros((rows,clmns))
matrix = matrix.astype(int)
print("Enter the matrix elements (by pressing enter): ")
for x in range (0,rows):
    for y in range (0,clmns):
        matrix[x][y] = input()
print ("Matrix entered is : \n %s"%matrix)
van_mat = vandermonde_matrix(matrix,clmns)
print("Vandermonde Matrix is:\n %s" %van_mat)


Enter number of rows in matrix: 3
Enter number of columns in matrix: 3
Enter the matrix elements (by pressing enter): 
1
2
3
4
5
6
7
8
9
Matrix entered is : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Vandermonde Matrix is:
 [[  1   4  27]
 [  4  25 216]
 [  7  64 729]]
