In [1]:
# Question 1: Write a function to compute 5/0 and use try/except to catch the exceptions


a = 5 
b = 0
try:
    c = a/b
    print(c)
except ZeroDivisionError:
     print("Division by zero not possible")


Division by zero not possible


In [2]:
# Question 2: Implement a Python program to generate all sentences where subject is in ["Americans",
# "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

output_list = [ (sub +' '+ verb + ' ' + obj) for sub in subjects for verb in verbs for obj in objects]
for op in output_list:
    print(op)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# Task 2

In [54]:
# Write a function so that the columns of the output matrix are powers of the input vector.
# The order of the powers is determined by the increasing boolean argument. Specifically, when
# increasing is False, the i-th output column is the input vector raised element-wise to the power
# of N - i - 1.


import numpy as np

def vandermonde_matrix(mtrx,n,b):
    if b=="false":
        mtrx=np.array(mtrx)
        for i in range(n):
            mtrx[:,i] **= n-i-1   
    elif b=="true":
        print("Entered True")
        mtrx=np.array(mtrx)
        for i in range(n):
            mtrx[:,i] **= n-i-1  
        mtrx[:,[0,n-1]] = mtrx[:,[n-1,0]]
    return mtrx.astype(int)

print("Enter array of elements")
arr=list(map(int,input().split()))
n=int(input("Enter n (no. of columns) "))
b = input("Enter true/false ")
print(b)
np_arr = np.array(arr)
z = np.zeros((n,len(arr)))
arr = z+arr #broadcasting
mat = vandermonde_matrix(arr.T,n,b)
print("Vandermonde Matrix is : \n%s" %mat)




Enter array of elements
1 2 3 4 5 6
Enter n (no. of columns) 4
Enter true/false false
false
Vandermonde Matrix is : 
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]
 [216  36   6   1]]
